<?php
$title = 'User Info';
$this->headTitle( $title );

// This provides a default CSS class and placeholder text for the title element:
$userName = $form->get( 'username' );
$userName->setAttribute( 'class', 'form-control' );
$userName->setAttribute( 'placeholder', 'Username' );

// This provides a default CSS class and placeholder text for the artist element:
$password = $form->get( 'password' );
$password->setAttribute( 'class', 'form-control' );
$password->setAttribute( 'placeholder', 'Password' );

// This provides CSS classes for the submit button:
$submit = $form->get( 'login' );
$submit->setAttribute( 'class', 'btn btn-primary' );

$form->setAttribute( 'action', $this->url( 'login', [ 'action' => 'index' ] ) );
$form->prepare();

?>
<div class="card">
    <div class="card-header">
        <h1>User: <?= $user->getId() ?></h1>
    </div>
    <div class="card-body">
		<?= $this->form()->openTag( $form ); ?>
        <div class="form-group">
			<?= $this->formLabel( $userName ) ?>
			<?= $this->formElement( $userName ) ?>
			<?= $this->V ?>
        </div>

        <div class="form-group">
			<?= $this->formLabel( $password ) ?>
			<?= $this->formElement( $password ) ?>
			<?= $this->formElementErrors()->render( $password, [ 'class' => 'help-block' ] ) ?>
        </div>

        <div class="text-right">
			<?php
			echo $this->formSubmit( $submit );
			echo $this->formHidden( $form->get( 'id' ) );
			echo $this->form()->closeTag();
			?>
        </div>
    </div>
    <div class="card-footer text-muted">
    </div>
</div>