<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
	<?= $this->headTitle( 'Laminas Albums' )->setSeparator( ' - ' )->setAutoEscape( false ) ?>

	<?= $this->headMeta()
	         ->appendName( 'viewport', 'width=device-width, initial-scale=1.0' )
	         ->appendHttpEquiv( 'X-UA-Compatible', 'IE=edge' )
	?>

    <!-- Le styles -->
	<?= $this->headLink(
		[
			'rel'  => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
			'href' => $this->basePath().'/img/favicon.ico'
		]
	)
	         ->prependStylesheet( $this->basePath( 'css/style.css' ) )
	         ->prependStylesheet( $this->basePath( 'css/bootstrap.min.css' ) )
	?>

    <!-- Scripts -->
	<?= $this->headScript() ?>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url( 'home' ) ?>">
                Laminas Albums
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
			<?= $this->navigation( 'navigation' )
			         ->menu()
			         ->setMinDepth( 0 )
			         ->setMaxDepth( 0 )
			         ->setUlClass( 'nav navbar-nav' ) ?>
        </div>
		<?php if( $this->identity() ) { ?>
            <form action="/user/logout" method="post">
                <button type="submit" class="btn btn-danger">Logout</button>
            </form>
		<?php } ?>
    </div>
</nav>
<?= $this->navigation( 'navigation' )
         ->breadcrumbs()
         ->setMinDepth( 0 )
         ->setPartial( 'partial/breadcrumb' ) ?>
<div class="container">
	<?php
	$FM = $this->flashMessenger()
	           ->setMessageOpenFormat(
		           '<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><div>'
	           )
	           ->setMessageSeparatorString( '</div><div>' )
	           ->setMessageCloseString( '</div></div>' );
	echo $FM->render( 'success', [ 'alert', 'alert-dismissible', 'alert-success' ] );
	echo $FM->render( 'info', [ 'alert', 'alert-dismissible', 'alert-info' ] );
	echo $FM->render( 'error', [ 'alert', 'alert-dismissible', 'alert-danger' ] );
	echo $this->content;
	?>
</div>
<?= $this->inlineScript()
         ->prependFile( $this->basePath( 'js/bootstrap.min.js' ) )
         ->prependFile( $this->basePath( 'js/jquery-3.5.1.min.js' ) ) ?>
</body>
</html>
