<?php
$title = 'Sign Up';
$this->headTitle( $title );

// This provides a default CSS class and placeholder text for the title element:
$userName = $form->get( 'username' );
$userName->setAttribute( 'class', 'form-control' );
$userName->setAttribute( 'placeholder', 'Username' );

// This provides a default CSS class and placeholder text for the artist element:
$password = $form->get( 'password' );
$password->setAttribute( 'class', 'form-control' );
$password->setAttribute( 'placeholder', 'Password' );

$passwordRetype = $form->get( 'password-retype' );
$passwordRetype->setAttribute( 'class', 'form-control' );
$passwordRetype->setAttribute( 'placeholder', 'Password Retype' );

// This provides CSS classes for the submit button:
$submit = $form->get( 'signup' );
$submit->setAttribute( 'class', 'btn btn-primary' );

$form->setAttribute( 'action', $this->url( 'signup', [ 'action' => 'index' ] ) );
$form->setAttribute( 'method', 'post' );
$form->setAttribute( 'autocomplete', 'off' );
$form->prepare();

?>
<div class="card">
    <div class="card-header">
        <h1><?= $title ?></h1>
    </div>
    <div class="card-body">
		<?php
		echo $this->form()->openTag( $form ); ?>
        <div class="form-group">
			<?= $this->formLabel( $userName ) ?>
			<?= $this->formElement( $userName ) ?>
			<?= $this->formElementErrors()->render( $userName, [ 'class' => 'help-block' ] ) ?>
        </div>

        <div class="form-group">
			<?= $this->formLabel( $password ) ?>
			<?= $this->formElement( $password ) ?>
			<?= $this->formElementErrors()->render( $password, [ 'class' => 'help-block' ] ) ?>
        </div>

        <div class="form-group">
			<?= $this->formLabel( $passwordRetype ) ?>
			<?= $this->formElement( $passwordRetype ) ?>
			<?= $this->formElementErrors()->render( $passwordRetype, [ 'class' => 'help-block' ] ) ?>
        </div>

        <div class="text-right">
			<?php
			echo $this->formSubmit( $submit );
			echo $this->formHidden( $form->get( 'id' ) );
			echo $this->form()->closeTag();
			?>
        </div>
    </div>
    <div class="card-footer text-muted">
        Already have a account? <a href="/login">Login</a>.
    </div>
</div>